[platformio]
default_envs = stor

[env:stor]
platform = ststm32
framework = stm32cube
board = stor_h723vg
board_build.ldscript = ldscript/STM32H723VGTX_FLASH.ld

build_unflags = -std=gnu++14 -std=gnu++11
extra_scripts = pre:cxx_flags.py
build_flags =
  -Wall
  -Wextra
  -Iinclude
  -DHSE_VALUE=25000000
  -DCFG_TUSB_MCU=OPT_MCU_STM32H7
  -DCFG_TUSB_OS=OPT_OS_NONE

upload_protocol = serial
monitor_speed = 115200
